### ISSUE TITLE
Upload key for the client

### ISSUE THREAD

**Issue by jweter** [mplusgg/MplusGG#2]
there doesn't seem to be anywhere to register for an upload key for the desktop client.

**Comment by Ruzzak** [comment]
@jweter 
In the upper right corner you can press the login button, select your region and login with Blizzard OAuth after successfully login in you can select upload runs.  You should now see a personal upload key.

**Comment by gwaldvogel** [comment]
I added an info text on the website to make it clear how to obtain your upload key. Thank you for your feedback.
